import { ThemeProvider } from 'next-themes';
import type { Metadata } from 'next';
import './globals.css';
import React from "react";

export const metadata: Metadata = {
    title: 'Portfolio Ethan COPIN',
    description: 'Generated by Next.js',
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body>
        <ThemeProvider attribute="class">
            {children}
        </ThemeProvider>
        </body>
        </html>
    );
}